version: '3.3'
services:
    frontend:
        container_name: frontend
        build: frontend #local folder
        ports:
            - 3000:3000
        stdin_open: true
        volumes:
            - ./frontend:/SWE-599/frontend
            - /SWE-599/frontend/node_modules
        restart: always
        depends_on:
            - nutch
        # environment:
        #     CHOKIDAR_USEPOLLING: 'true'
        networks:
            - local
    solr:
        container_name: solr
        image: 'solr:8.5.2'
        ports:
            - '8983:8983'
        volumes:
            - ./nutch-conf/schema.xml:/opt/solr/server/solr/configsets/_default/conf/schema.xml
            - ./nutch-conf/managed-schema:/opt/solr/server/solr/configsets/_default/conf/managed-schema
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - nutch
        environment:
            JVM_OPTS: >
                -XX:-UseLargePages


        networks:
            - local
    nutch:
        container_name: nutch
        image: 'apache/nutch:latest'
        depends_on:
            - solr
        environment:
            - JAVA_HOME=/usr/lib/jvm/java-11-openjdk
        working_dir: /root/nutch
        command: '/root/nutch/bin/nutch startserver -port 8081 -host 0.0.0.0'
        volumes:
            - ./nutch-conf/index-writers.xml:/root/nutch/conf/index-writers.xml
            - ./nutch-conf/nutch-site.xml:/root/nutch/conf/nutch-site.xml
            - ./nutch-conf/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt
            - ./nutch-conf/seed.txt:/root/nutch/urls/seed.txt
        ports:
            - '8080:8080'
            - '8081:8081'
        networks:
            - local
    cors:
        container_name: cors
        build: cors #local folder
        ports:
            - '4545:80'
        depends_on:
            - nutch
        networks:
            - local
    cors-solr:
        container_name: cors-solr
        build: cors-solr #local folder
        ports:
            - '4646:88'
        depends_on:
            - solr
        networks:
            - local
networks:
    local:
        driver: bridge
